### ISSUE TITLE
compatible with redmine 4.0 ?

### ISSUE THREAD

**Issue by ka7** [jperelli/Redmine-Periodic-Task#88]
( did not try, but the README.md does not tell anything about 4.x )

**Comment by jperelli** [comment]
@ka7 I didn't try it, I think it will not work, but please test it if you can and let us know!

**Comment by 83166807934** [comment]
Hi, dear friend.

I've tried on 4.0 and it didn't work because redmine 4.0 uses rails 5.2 and there are some deprecated functions/methods... like:

**### NoMethodError: undefined method `before_filter' for PeriodictaskController:Class
Did you mean?  before_action**

and others...

Thanks a lot for your plugin... It's great!!!

Fabiano

**Comment by jperelli** [comment]
@yzzy has fixed the plugin to work with redmine Redmine versions 4.0.0, 3.4.7, 3.3.9

**Comment by 83166807934** [comment]
Cheers man... thanks a lot!!! 
Works perfectly!
